# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_01_prepare.py
    - data/data.xml
    - configs/config.yaml
    - src/utils/common.py
    - src/utils/data_mgnt.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - artifacts/prepared/test.tsv
    - artifacts/prepared/train.tsv

  featurize:
    cmd: python src/stage_02_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_02_featurization.py
    - artifacts/prepared/test.tsv
    - artifacts/prepared/train.tsv
    - configs/config.yaml
    - src/utils/common.py
    - src/utils/featurize.py
    params:
    - featurize.max_params
    - featurize.ngrams
    outs:
    - artifacts/features/test.pkl
    - artifacts/features/train.pkl

  train:
    cmd: python src/stage_03_train.py --config=configs/config.yaml --params=params.yaml
    deps:
    - src/stage_03_train.py
    - artifacts/features/train.pkl
    - configs/config.yaml
    - src/utils/common.py

    params:
    - train.seed
    - train.n_est
    - train.min_split
    outs:
    - artifacts/model/model.pkl
